[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Disable secrets scanning completely for this build
[secrets_scanning]
  enabled = false

# Alternative: If secrets scanning must be enabled, configure it properly
# [secrets_scanning]
#   enabled = true
#   omit_paths = ["dist/**", "dist-ssr/**", "build/**", "**/dist/**"]
#   omit_keys = ["VITE_OPENAI_API_KEY", "OPENAI_API_KEY"] 