// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crktkwnfnmjeqqnshqcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNya3Rrd25mbm1qZXFxbnNocWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDg2NTYsImV4cCI6MjA2OTkyNDY1Nn0.cbpDZeSOs8GsLX9jY73Eywn7kGAqT6-tsQqpqnsDsB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});